# contains all needed parameters for all files

dt: 0.25
random_seed: 0
config_file: '/home/avillaflor/probcoll/robots/rccar/params_rccar.yaml' # Should just be this file
exp_dir: '/home/avillaflor/probcoll/experiments/rccar'
exp_name: 'bair_car_hallway_async'

##########################
### Probcoll algorithm ###
##########################

probcoll:
  T: 24 # timesteps per trajectory
  max_iter: 500
  logger: 'debug' # debug/info/fatal what level to log
  is_training: True
  asynchronous_training: True
  label_with_noise: True # if false, saves desired controls (i.e. without control_noise)
#  init_data: '/home/avillaflor/gps_quadrotor/experiments/rccar/init_data_real'

  conditions:
    repeats: 20 # TODO
    num_test: 1
    randomize_conds: False
    randomize_reps: True

    default:
      cmd_steer: [49.5]
      cmd_vel: [0.]

    range:
      cmd_vel:
        min: [0]
        max: [0]
        num: [1]

    perturb: # repetition perturbations
      cmd_vel: [0.]
    
######################
### Probcoll model ###
######################
    
model:
  T: 8 # how many timesteps to predict
  logger: 'debug' # debug/info/fatal what level to log
  pct_coll: 0.5 # rebalancing trajectories
  coll_weight_pct: 0.5 # reweight collision and no collision samples in cost
  control_range:
    lower: [0., -17.]
    upper: [99., 17.]
  # what to use as input to prediction model
  U_order: ['cmd_steer', 'cmd_vel']
  O_im_order: ['camera'] # / 'back_camera'
  O_vec_order: []
  output_order: ['collision'] # taken from observations O
  num_O: 1
  scale_O_im: True
  center_O_im: False 
  # NN training parameters
  device: 3
  gpu_fraction: 0.8 #TODO
  reset_every_train: False # every time train is called, reinitialize weights?
  learning_rate: 1.e-3
  beta1: 0.9 # For ADAM
  beta2: 0.999 # For ADAM
  batch_size: 32
  display_steps: 100 
  val_freq: 0.1 # How often you compute validation
  val_steps: 10  # How many steps you do on validation 
  steps: 1000
  val_pct: 0.1 # Percent of the data stored as validation

  dtype: 'float32'
  reg: 1.e-5
  num_bootstrap: 1
  prob_coll_strictly_increasing: True # True / False 
  mask: 'all' # all / last

  image_graph:
    graph_type: 'cnn'
    filters: [32, 64, 64]
    kernels: [8, 4, 3]
    strides: [4, 2, 1]
    padding: 'SAME' 
    use_batch_norm: True
    conv_activation: 'relu'
    output_activation: 'relu' 
#    output_activation: 'relu'
#    output_activation: 'spatial_softmax'
#  action_graph:
#    graph_type: 'fc' # fc / rnn
#    hidden_layers: []
#    output_dim: 48 # Has to be divisible by T
#    hidden_activation: 'relu'
#    dropout: 0.9
  observation_graph:
    hidden_activation: 'tanh' 
    output_dim: 128 # This is the hidden size of the rnn
  
  action_graph:
    graph_type: 'rnn' # fc / rnn
    num_cells: 1
    cell_type: 'mulint_rnn' #rnn / mulint_rnn
#    dropout: 0.8 # pct keep
#    cell_args: # If you need to pass variables to cells 

  output_graph: # Must have dropout 1.0
    graph_type: 'fc' # fc / rnn

#################################################
### Planning objective and optimizer settings ###
#################################################

planning:
  cost:
    coll_cost:
      cost: square # square
      weight: [0., 10.] # TODO
      std_weight: 0.0
      pre_activation: True # wether std is before or after activation (sigmoid)
    
    control_cost:
      des: [49.5, 8.] # TODO: hard-coded order: steering then speed
      cost: square
      weight: [0.001, 1.0]     
  
  epsilon_greedy:
    endpoints: [[0, 1.0], [50, 1.0], [150, 0.01]]
    #    endpoints: [[0, 1.0], [25, 1.0], [250, 0.1], [500, 0.01]]
    outside_value: 0.00
    lower: [20., 8.]
    upper: [80., 8.]

  control_noise:
    type: 'zero' # zero / gaussian / uniform

    zero: {}
    gaussian:
      std: [3.0, 0.3]
    uniform:
      lower: [-5., 0.]
      upper: [5., 0.]
  
  num_dp: 1 # number of dropout passes to average over
  planner_type: 'random' # random / primitives / cem / random_policy
  # specific to your primitives code
  primitives:
    steers: [30., 40., 50., 60., 70.]
    speeds: [16.]
    num_splits: 3

  # control range for your planning algorithms
  control_range:
    lower: [20., 4.]
    upper: [80., 12.]

  random:
    K: 2048 # number of actions to sample from

  cem:
    init_M: 1024 # number of actions to sample from
    M: 256
    K: 16 # top actions you select
    num_iters: 4 # does not include first sample    
    eps: 0.01 # to ensure covariance is PD

  # TODO: other planning methods here
  visualize: False
  topics:
    debug_cost: 'debug_cost' # visualization_msgs/MarkerArray
    debug_cost_probcoll: 'debug_cost_probcoll' # visualization_msgs/MarkerArray
  
#############
### World ###
#############

world:
#  plot: False
  logger: 'info' # debug/info/fatal what level to log for world and agent
  randomize: True
  sim: True 
  do_back_up: False
#  do_back_up: True

  back_up:
    cmd_steer: [44.5, 54.5]
    cmd_vel: -12
    duration: 3.0

  testing:
    itr_freq: 2
    positions: []
#    positions: [[-95., 0., -0.6], [-80., 60., -0.6], [13., 48., -0.6], [0., -20., -0.6]]
#    positions: [[40., -35., 0.2], [-40., -35., 0.2], [40., 20., 0.2], [-40., 20., 0.2]]
#    positions: [[40., -40., 0.2], [40., 20., 0.2]]
#    positions: [[40., 20., 0.2]]
#    position_ranges: [[[40., -40., 0.2, 0.0], [40., 40., 0.2, 6.28]]]

sim:
  srv: 'sim_env'
  sim_env: 'hallway' # hallway / cory2 / square
  launch_file: '/home/avillaflor/probcoll/robots/rccar/ros/launch/car_srv_sim.launch'
  dt: 0.25
  steeringClamp: 45.0
  accelClamp: 12.0
  mass: 800.0
  first_person: True
  p: 2000.0
  i: 0.0
  d: 0.0

######################################################
########### States, controls, observations ###########
######################################################

X:
  dim: 9
  order: ['cmd_steer', 'cmd_vel', 'position', 'orientation']

  cmd_steer: {idx: 0, dim: 1, min: 0, max: 100}
  cmd_vel: {idx: 1, dim: 1, min: 6}
  position: {idx: 2, dim: 3}
  orientation: {idx: 5, dim: 4}

U:
  dim: 2
  order: ['cmd_steer', 'cmd_vel']

  cmd_steer: {idx: 0, dim: 1, min: 0, max: 100}
  cmd_vel: {idx: 1, dim: 1, min: 6}

O:
  use_depth: True

  dim: 4610
  order: ['camera', 'back_camera', 'vel', 'collision']

  camera:
    idx: 0
    dim: 2304
    height: 64
    width: 36
    num_channels: 1
    noise: 0.01
  back_camera:
    idx: 2304
    dim: 2304
    height: 64
    width: 36
    num_channels: 1
    noise: 0.01
  vel: {idx: 4608, dim: 1}
  collision: {idx: 4609, dim: 1, buffer: 0.0}

##################
### ros topics ###
##################

rccar:
  topics:
    camera: 'image' # sensor_msgs/Image
    depth: 'depth' # sensor_msgs/Image
    cmd_steer: 'cmd/steer' # std_msgs/Float32
    cmd_vel: 'cmd/vel' # std_msgs/Float32
    pred_image: 'prediction/image'
    collision: 'crash' # std_msgs/Empty
    good_rollout: 'good_rollout' # std_msgs/Empty
    bad_rollout: 'bad_rollout' # std_msgs/Empty
    teleop_cmd_steer: 'teleop_cmd/steer' # std_msgs/Float32
    teleop_cmd_vel: 'teleop_cmd/motor' # std_msgs/Float32
    reset: 'reset' #std_msgs/Empty

    # below topics that are just recorded
    cmd_motor: 'cmd/motor'
    encoder: 'encoder'
    motor: 'motor'
    state: 'state'
    steer: 'steer'
    vel: 'vel'
    # and for debugging
    debug_cost: 'debug_cost' # visualization_msgs/MarkerArray
    debug_cost_probcoll: 'debug_cost_probcoll' # visualization_msgs/MarkerArray
