# contains all needed parameters for all files

dt: [0.25]
random_seed: [0]

##########################
### Probcoll algorithm ###
##########################

probcoll:
  planner_type: ['primitives'] # primitives / cem / teleop / straight / lattice
  control_noise:
    type: ['uniform'] # zero / gaussian / uniform

  cost:
    weight: [1e3] # TODO
    eval_cost: ['speed * speed * sigmoid(probs_mean + 0.0*probs_std)']

######################
### Probcoll model ###
######################
    
model:
  T: [6] # how many timesteps to predict

  learning_rate: [0.001]
  beta1: [0.8] # For Adam
  beta2: [0.999] # For Adam

  reg: [0.0]
  num_bootstrap: [1]
  num_dropout_passes: [10]
  mask: ["all"] # all / last

#################################################
### Planning objective and optimizer settings ###
#################################################

planning:
  cost_velocity:
    u_weights: [[1., 1.]] # [0.0001, 0.2]

  primitives:
    steers : [[40., 45., 50., 55., 60.]]
    speeds : [[16.]]
    num_steers : [2]
  # TODO: other planning methods here

######################################################
########### States, controls, observations ###########
######################################################

O:
  use_depth: [True, False]
