# contains all needed parameters for all files

dt: 0.25
random_seed: 0

exp_dir: '/home/adam/probcoll/experiments/rccar'
exp_name: 'bair_car_test'

##########################
### Probcoll algorithm ###
##########################

probcoll:
  T: 28 # timesteps per trajectory
  max_iter: 20
  planner_type: 'primitives' # primitives / cem / teleop / straight / lattice

  control_noise:
    type: 'uniform' # zero / gaussian / uniform

    zero: {}
    gaussian:
      std: [3.0, 0.3]
    uniform:
      lower: [-5., 0.]
      upper: [5., 0.]

  label_with_noise: True # if false, saves desired controls (i.e. without control_noise)
#  init_data: '/home/adam/gps_quadrotor/experiments/rccar/init_data_real'
#  init_epochs: 100

  cost:
    weight: 1e3 # TODO
    eval_cost: 'speed * speed * sigmoid(probs_mean + 0.0*probs_std)'
    pre_activation: True

  conditions:
    repeats: 10 # TODO
    num_test: 1
    randomize_conds: False
    randomize_reps: True

    default:
      cmd_steer: [49.5]
      cmd_vel: [0.]

    range:
      cmd_vel:
        min: [0]
        max: [0]
        num: [1]

    perturb: # repetition perturbations
      cmd_vel: [0.]
    
######################
### Probcoll model ###
######################
    
model:
  T: 6 # how many timesteps to predict

  control_range:
    lower: [0., 0.]
    upper: [99.0, 99.0]
  
  # what to use as input to prediction model
  X_order: []
  U_order: ['cmd_steer', 'cmd_vel']
  O_order: ['camera']
  output_order: ['collision'] # taken from observations O

  # NN training parameters
  device: 0
  gpu_fraction: 0.4 #TODO
  reset_every_train: True # every time train is called, reinitialize weights?
  early_stopping: False # if True, only saves model each epoch if it's the lowest cost on validation for all epochs
  learning_rate: 0.001
  batch_size: 16
  display_batch: 200
  val_freq: 500 # How often you compute validation
  val_steps: 200  # How many steps you do on validation 
  steps: 10000
  val_pct: 0.2

  # How to save tfrecords
  save_type: 'fixedlen' # fixedlen
  
  reg: 0.
  num_bootstrap: 1
  num_dropout_passes: 10
  prob_coll_strictly_increasing: True 
  recurrent: True
  mask: "all"

  observation_graph:
    graph_type: "cnn"
    filters: [4, 4, 4]
    kernels: [3, 3, 3]
    strides: [2, 2, 2]
    padding: "VALID" 
    conv_activation: "relu" 
    output_activation: "None"
       
#  action_graph:
#    graph_type: 'fc' # fc / rnn
#    hidden_layers: [16, 16]
#    output_dim: 24 # Has to be divisible by T
#    hidden_activation: "relu"
#    output_activation: "None"
#    dropout: 0.7
  
  action_graph:
    graph_type: 'rnn' # fc / rnn
    num_cells: 1
    num_units: 16 # state_size
    cell_type: 'mulint_rnn' #rnn / mulint_rnn
    dropout: 0.7 # pct keep
#    cell_args: # If you need to pass variables to cells 

  output_graph: # Must have dropout 1.0
    graph_type: 'fc' # fc / rnn
    hidden_layers: []
    output_dim: 1 # TODO
    hidden_activation: "None"
    output_activation: "None"
    dropout: 1.0 # pct keep


#################################################
### Planning objective and optimizer settings ###
#################################################

planning:
  cost_velocity:
    u_des: [49.5, 16.] # TODO: hard-coded order: steering then speed
    u_weights: [1., 0.2] # [0.0001, 0.2]

  primitives:
    steers : [30., 40., 50., 60., 70.]
    speeds : [16.]
    num_steers : 3
  # TODO: other planning methods here

#############
### World ###
#############

world:
#  plot: False
  randomize: True

  back_up:
    cmd_steer: [40, 60]
    cmd_vel: -12
    duration: 4.

sim:
  dt: 0.25
  steeringClamp: 45.0
  engineClamp: 1000.0
  mass: 800.0
  first_person: True

######################################################
########### States, controls, observations ###########
######################################################

X:
  dim: 2
  order: ['cmd_steer', 'cmd_vel']

  cmd_steer: {idx: 0, dim: 1, min: 0, max: 100}
  cmd_vel: {idx: 1, dim: 1, min: 6}

U:
  dim: 2
  order: ['cmd_steer', 'cmd_vel']

  cmd_steer: {idx: 0, dim: 1, min: 0, max: 100}
  cmd_vel: {idx: 1, dim: 1, min: 6}

O:
  dim: 577
  order: ['camera', 'collision']

  camera:
    idx: 0
    dim: 576
    height: 32
    width: 18
    noise: 0.01
  collision: {idx: 576, dim: 1, buffer: 0.0}

##################
### ros topics ###
##################

rccar:
  config_file: '/home/adam/probcoll/robots/rccar/params_rccar.yaml' # Should just be this file
  launch_file: '/home/adam/probcoll/robots/rccar/ros/launch/car_srv_sim.launch'
  sim: True 
  srv: 'sim_env'

  topics:
    camera: 'image' # sensor_msgs/Image
    depth: 'depth' # sensor_msgs/Image
    cmd_steer: 'cmd/steer' # std_msgs/Float32
    cmd_vel: 'cmd/vel' # std_msgs/Float32
    pred_image: 'prediction/image'
    collision: 'crash' # std_msgs/Empty
    good_rollout: 'good_rollout' # std_msgs/Empty
    bad_rollout: 'bad_rollout' # std_msgs/Empty
    teleop_cmd_steer: 'teleop_cmd/steer' # std_msgs/Float32
    teleop_cmd_vel: 'teleop_cmd/motor' # std_msgs/Float32
    reset: 'reset' #std_msgs/Empty

    # below topics that are just recorded
    cmd_motor: 'cmd/motor'
    encoder: 'encoder'
    motor: 'motor'
    state: 'state'
    steer: 'steer'
    vel: 'vel'
    # and for debugging
    debug_cost: 'debug_cost' # visualization_msgs/MarkerArray
    debug_cost_probcoll: 'debug_cost_probcoll' # visualization_msgs/MarkerArray

